version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
       # <port on localhost>:<port on container>
       - 8000:8000
    # to sync changes from development
    volumes:
      - ./:/usr/src/app:ro
    # env_file:
    #   - ./.env
    # OR
    environment:
      # Database Environment Variables
      - DATABASE_HOSTNAME=postgres
      - DB_PASSWORD=password123
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi
      - DB_USERNAME=postgres

      # Authorization Environment Variables 
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    # overrides the uvicorn app.main:app present in Dockerfile CMD layer
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
