version: "3"
services:
  api:
    image: getrohitansh/fastapi
    depends_on:
      - postgres
    ports:
       # <port on localhost>:<port on container>
       # at port 80 we can use web browser
       - 80:8000
    
    # env_file:
    #   - ./.env
    # OR
    environment:
      # Database Environment Variables
      # ${} looks for these values in our host/linux machine
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DB_USERNAME=${DB_USERNAME}

      # Authorization Environment Variables 
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    # overrides the uvicorn app.main:app present in Dockerfile CMD layer
    command: >
      sh -c "alembic upgrade head"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
